### ISSUE TITLE
ReferenceError : vis is not defined

### ISSUE THREAD

**Issue by Dearworld1** [dataiku/dss-plugin-graph-analytics#3]
Dear Friend,

I'm trying to folow your guide but at the final step wright  before the visualization step, I have an error message  "ReferenceError : vis is not defined", I'm a beginner and I don't now what to do, and there is no documentation on that error.

Do you have some idea on how to fix this ? Otherwise tables are just like in your tutorial.

Thank you and have a  nice day 😊

Steph

**Comment by StanislasGuinel** [comment]
Hi, you may get this error if your browser is not connected to the internet because Vis is a javascript graph visualisation library that is loaded externally through the internet.
